# Change these first
owner: incloodo # Your GitHub organization or username, where this repository lives
repo: status_pages # The name of this repository

sites:
  # ------- STAGING PAGES --------------
  - name: Incloodo Staging Services
    url:  http://staging.incloodo.com/api/json/v1/interests
    expectedStatusCodes:
      - 200
  - name: Incloodo Stating Login
    url: http://staging.incloodo.com/api/json/v1/authentication/login   
    method: POST
    body: '{ "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}"}'
    expectedStatusCodes:
      - 404
  # ------- PRODUCTION PAGES -----------
  - name: Incloodo Production Services
    url:  https://server.incloodo.com/api/json/v1/interests
    expectedStatusCodes:
      - 200
  - name: Incloodo Production Login
    url: https://server.incloodo.com/api/json/v1/authentication/login
    method: POST
    body: '{ "username": "$USERNAME", "password": "$PASSWORD" }'
    expectedStatusCodes:
      - 404
    
assigness:
  - cannavit
  - incloododev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   cname: demo.upptime.js.org
  baseUrl: /status_pages
  logoUrl: https://media-exp1.licdn.com/dms/image/C4D0BAQHxQG6swEbZWQ/company-logo_200_200/0/1625816847340?e=2147483647&v=beta&t=GYml_szIsuQOfOzV_-TwnkHzTcAUIpNV1OCxPNUn4DY
  name: Incloodo
  introTitle: "**Incloodo** Status Pages"
  introMessage: This page monitors the Production and Staging sites 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
